### ISSUE TITLE
Wrong Size for Extra Data

### ISSUE THREAD

**Issue by scoronado12** [flathub/com.adobe.Flash-Player-Projector#17] opened 2019-05-29 02:48 UTC
I have received this error when trying to install flash via Flathub

![image](https://user-images.githubusercontent.com/9601750/58525694-b1d53f00-819a-11e9-8288-274f166df5d3.png)

**Comment by hadess** [comment] 2019-05-29 06:45
Duplicate of #15

**Closed by hadess** 2019-05-29 06:45 UTC
